### ISSUE TITLE
complex.yml referenced in readme is missing

### ISSUE THREAD

**Issue by thomasdarimont** [oauth-wg/oauth-selective-disclosure-jwt#264]
The example mentioned in the readme does not work since the complex.yml file is missing:
```
sd_jwt sd_jwt/examples/complex.yml
````
yields:
```
$ sd_jwt sd_jwt/examples/complex.yml
Traceback (most recent call last):
  File "/home/tom/.local/bin/sd_jwt", line 170, in <module>
    example = load_yaml_example(_args.example)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tom/.local/bin/sd_jwt", line 160, in load_yaml_example
    with open(_args.example, "r") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'sd_jwt/examples/complex.yml'
````

**Comment by danielfett** [comment]
Grüße ins Saarland and thanks for catching that. The examples was renamed, we'll update the readme.

**Comment by danielfett** [comment]
Thanks again for catching this. I'll close this issue as the code will be moved to https://github.com/danielfett/sd-jwt. The Readme will be adapted accordingly in #273.
